spring.application.name=demo

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=YOUR_BASE64_SECRET_KEY
jwt.expiration=86400000


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_USER_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



//DB setup 

//npx neonctl@latest init

//npg_ziKTEogh2vy9

#Host
#ep-jolly-surf-au1yc5qy.c-10.us-east-1.aws.neon.tech
#Database
#neondb
#Role
#neondb_owner
#Password
#************
#Pooler host
#ep-jolly-surf-au1yc5qy-pooler.c-10.us-east-1.aws.neon.tech

#postgresql://neondb_owner:npg_ziKTEogh2vy9@ep-jolly-surf-au1yc5qy.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require